config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'pages#profile'
  resources :creations, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creation.rb
class Creation < ApplicationRecord

   belongs_to :user
   has_many_attached :photos
   has_many_attached :images

  validates :name, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :creations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/creations_controller.rb
class CreationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @creations = Creation.all
  end

  def show
    @creation = Creation.find(params[:id])
  end


  def edit
    @creation = current_user.creations.find(params[:id])
  end

  def update
    @creation = Creation.find(params[:id])
    @creation.update(creations_params)
      redirect_to creations_path
  end

  private

  def creations_params
    params.require(:creation).permit(:name, :description, photos: [], images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creations_helper.rb
module CreationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/creations/_form.html.erb
<div class="form-edit">
  <%= simple_form_for(@creation) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text, autofocus: true, :input_html => {:rows => 5} %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :images, as: :file, input_html: { multiple: true } %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/creations/edit.html.erb
<div class="edit-page">
  <h1>Edit your creation</h1>
</div>

<%= render "form" %>

<div class="button">
  <%= link_to "Back", creations_path %>
</div>

app/views/creations/index.html.erb
<div class="link">
  <%= link_to 'On her way', root_path %>
</div>

<div class="links">
  <%= link_to 'Charles Durand', about_path %> ,  <%= link_to 'Cards', creations_path %>
</div>

<div class="cards">
  <% @creations.each do |creation|%>
        <div class="card1">
          <% creation.images.last(1).each do |image| %>
            <%= cl_image_tag image.key, crop: :fill %>
          <% end %>
            <div class="creations">
              <%= link_to creation.name, creation_path(creation) %>
            </div>
              <% if current_user %>
                <div class="edit">
                  <%= link_to 'Edit', edit_creation_path(creation.id)  %>
                </div>
              <% end %>
        </div>
  <% end %>
</div>



<div class="footer">
  <a href="https://www.instagram.com/charlesdur.nd/">instagram</a>
</div>

app/views/creations/show.html.erb
<div class="link">
  <%= link_to 'On her way', root_path %>
</div>

<div class="links">
  <%= link_to 'Charles Durand', about_path %>  ,  <%= link_to 'Cards', creations_path %>
</div>


<div class="show">
  <div class="tour">
    <%= render partial: 'shared/svgs/tour' %>
      <h1><%= @creation.name %></h1>
      <p><%= @creation.description %></p>
  </div>


  <div class="photo1">
    <% @creation.photos.last(2).each do |photo| %>
    <div class="photo2">
      <%= cl_image_tag photo.key, crop: :fill %>
    </div>
    <% end %>
  </div>

</div>


<div class="footer-show">
  <a href="https://www.instagram.com/charlesdur.nd/">instagram</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charles Durand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="link">
  <%= link_to 'On her way', root_path %>
</div>

<div class="links">
  <%= link_to 'Charles Durand', about_path %>   ,  <%= link_to 'Cards', creations_path %>
</div>


    <div class="bio">
      <h1>“Elles se bousculent, s’illustrent et se perdent, indifférentes - fuites en avant.
        <br> <em>(Retourne-toi).</em>
        <br>Je suis de celles, victimes de la houle de leurs pensées : tantôt joyeuses, maintenant funestes, alors futiles ou pleines de vacuité, qui cherchent des indices au hasard.
        <br>C’est le jeu. Du coq à l'âne, enroulée dans un fil, je me perds en pensées, en
        pépites de folie qui ne manquent pas de m'étonner.
        <br> <em>(Retourne-toi).</em>
        <br>Leurs
        messages m’ourlent les doigts, s’épanouissent, s’étiolent, évanescentes.
        Mue par la curiosité, je vous vois, je vous dévoile.”
      </h1>
    </div>


  <div class="signature">
    <%= render partial: 'shared/svgs/writing' %>
  </div>

app/views/pages/contact.html.erb
<div class="link">
  <%= link_to 'On her way', root_path %>
</div>

<div class="links">
  <%= link_to 'Charles Durand', about_path %>, <%= link_to 'Cards', onherway_path %>
</div>


<div class="show">
    <div class="tour">
<%= render partial: 'shared/svgs/tour' %>
        <h1>Creation 1</h1>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
    </div>


  <div class="photo1">
      <%= image_tag("creation2.jpg") %>
      <h1>1</h1>
    </div>

    <div class="photo2">
      <%= image_tag("creation1.jpg") %>
      <h1>2</h1>
    </div>
  </div>


<div class="footer">
<a href="https://www.instagram.com/charlesdur.nd/" style='font-size:15px'>instagram</a>, <a href="mailto: hi@charlesdurand.com" style='font-size:15px'>contact</a></ul>
</div>

app/views/pages/home.html.erb
    <div class='writing'>
      <h1> <%= link_to  "Charlie's on her way", creations_path %> </h1>
    </div>

    <%= video_tag "newvideo.mov", playsinline: true, autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>

app/views/pages/onherway.html.erb
<div class="link">
  <%= link_to 'On her way', root_path %>
</div>

<div class="links">
  <%= link_to 'Charles Durand', about_path %>, <%= link_to 'Cards', onherway_path %>
</div>

<div class="cards">
  <div class="card1">
    <%= image_tag("creation2.jpg") %>
  </div>

  <div class="card2">
    <%= image_tag("creation 3.jpg") %>
  </div>

  <div class="card3">
    <%= image_tag("creation2.jpg") %>
  </div>

</div>

<div class="creations">
  <div class="creation1">
    <h1>creation one</h1>
  </div>
  <div class="creation2">
    <h1>creation two</h1>
  </div>
  <div class="creation3">
    <h1>creation three</h1>
  </div>
</div>

<div class="footer">
<a href="https://www.instagram.com/charlesdur.nd/" style='font-size:15px'>instagram</a>, <a href="mailto: hi@charlesdurand.com" style='font-size:15px'>contact</a></ul>
</div>

app/views/pages/profile.html.erb
<div class="hello">
  <h1>Charles Durand</h1>
</div>

<div class="profile">
  <div class="profilecards">

    <div class="pcards">
      <%= link_to "Cards", creations_path, class: "nav-link" %>
    </div>

    <div class="pcards">
      <%= link_to "Login", user_session_path, class: "nav-link" %>
    </div>

    <div class="pcards">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </div>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/svgs/_writing.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.1.2, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 841.7 612" style="enable-background:new 0 0 841.7 612;" xml:space="preserve">
<style type="text/css">
  .st0{fill:#451033;}
</style>
<g id="Calque_2_1_">
  <g id="XMLID_1_">
    <g>
      <path class="st0" d="M295.1,163.6c3.6-9.6,53.5-1.6,21.4-19.7c-3.1,1.1-11.5-15.6-12.5-8.6c-1.7,13.3-6-7.4,0.7-10.6
        c5.2,19.5,56,30.3,3.4,37.2c-4,1.9-8.8,1.3-12.7,6C293.1,168.2,294,165.7,295.1,163.6z"/>
      <path class="st0" d="M279.5,135.1c0.8-1.1,9.9-1.4,4.8,5c-3.8,3.7-5.3-4.5-6,8.2C289.3,153.4,265.2,155.6,279.5,135.1z"/>
      <path class="st0" d="M276.4,82.6c0.5-6.5,9.9-11.3,5.2,6l-2.3-0.6c0.4-1.7,0.6-3.5,0.5-5.7c-0.9,2.6-2,5.8-2.9,8.9l-2.5-0.7
        C275.1,88,275.8,85.3,276.4,82.6z"/>
      <path class="st0" d="M275.7,90.9c0.4,0.1,0.8,0.2,1.2,0.3c-0.2,0.5-0.6,1.3-1,2.3c-0.7,1.9-1.1,3.3-1.3,3.9
        c-0.4,1.5-1.1,3.7-2.2,6.7c1.8-3.6,3.7-7.5,5.3-11.9c0.6-1.5,1.1-2.9,1.5-4.3l2.3,0.6c-0.5,2-1.2,4.3-2.2,6.7
        c-1.1,2.8-2.4,5.1-3.6,7.1c-0.6,1.5-1.3,3.1-2,4.6c-0.8,1.9-1.6,3.7-2.5,5.5c-2.9,5-6.1,11.5-8.5,19.4c-2.9,9.4-3.9,17.7-4.2,24
        c-0.6,0.3-1.2,0.4-1.6,0.2c-1.6-0.5-1.7-4-1.8-5.3c-0.3-6.9,15.2-49.8,19.1-60.4C274.8,90.7,275.3,90.8,275.7,90.9z"/>
      <path class="st0" d="M243.8,124.3c5.2,4-4.8,9.7-7.2,21.8l-2.9-0.5c0.4-1.9,1-4.2,2-6.9c4.9-8.2-0.6-2.3-2.6,3.8
        C226.6,149.4,236.1,125.9,243.8,124.3z"/>
      <path class="st0" d="M236.6,146.2c1.2,9.3-4.9,10-2.9-0.5L236.6,146.2z"/>
      <path class="st0" d="M227.9,136.3c15,7.2-61.4,40.1-45.1,16.3c-0.6,11.7,28.7-0.6,43.2-12.7c-4.5-4.7-24.6,2.9-30.5,10.6
        C183.5,147.2,219.9,130.3,227.9,136.3z"/>
      <path class="st0" d="M146.1,153.6c0.2,2.8-6.1,9.8,0,10.6c5.1,0,23.8-7.7,12.2-1.2c-44.6,22.8,20.1-47.9-50.6,9.6
        c-1.5,1.5-8,10.2-13.4,11c-4.2-1.8,14.1-16.8,18.2-20.2c11-14.1,19-19,33.8-37.9c1.1-1.3,2.2-2.6,3.4-3.8
        c48.2-54.1,73.8-79.9,76.7-77.6c1.3,1-1.7,7.3-8.8,18.8c-2.6-2.2,3.8-7.6,6-13.4c-14.7,7.3-26.8,27-39.4,37.9
        c-3.2,4.6-9.9,11.2-14.6,16.1c-0.2,0.5-1.3,2.6-2.6,2.9c-13.7,17-25.3,28.3-43,49.4c1.8,0.3,3.8-3.3,7.8-4.8c0,0.1,0.2,0,0.6-0.2
        c-0.2,0.1-0.4,0.1-0.6,0.2C131.8,150.4,149.6,138.8,146.1,153.6z"/>
      <path class="st0" d="M131.8,150.9c0.2-0.1,0.4-0.1,0.6-0.2C132,150.9,131.8,151,131.8,150.9z"/>
      <path class="st0" d="M165.1,34.9c-8.7,3.4-17.5,8.2-22.3,10.8c-7.8,4.2-17.6,10-28.6,17.8c-10,7-24.3,18.1-39.3,34
        c-9.1,9.7-45.9,48.9-36.5,63.8c7.1,11.3,40,7.9,40,8.4c0,0,0,0-0.1,0c-2.1,0.4-6.2,1.1-12.8,2.4c-20.4,4.2-38.6-7.3-28.8-30
        c12.4-25.5,25.2-38.4,40.3-51.4c8.5-12.1,49.8-40.3,67.2-47.3c3.9-2,8-4,12.2-5.9c5.8-2.7,11.5-5,16.9-7.1
        c1.4-0.6,2.7-1.1,4.4-1.7c4.3-1.6,4.8-1.5,9.3-3c4-1.4,4.8-1.9,7.2-2.3c1.9-0.3,3.6-0.3,4.7-0.3c-0.6,0.1-1.2,0.3-1.8,0.4
        c-4.8,1.1-9.2,2.6-13.3,4.2c-2,0.8-5.2,2-7.2,2.8C172.8,31.9,166.3,34.4,165.1,34.9z"/>
    </g>
  </g>
  <path class="st0" d="M430.9,178c9.5-8.3,15.4-13.7,26.6-23c22-18.5,33.1-27.7,34.2-28.6c17-13.2,22.8-16,22.5-21.4
    c-0.3-6.4-9.1-7-23-21.1c-5.8-5.9-4.3-5.9-13.3-16.2c-12.5-14.4-21.8-21.9-24.5-24c-11.6-9.1-18.6-14.6-23.5-12.3
    c-4.2,2-1.8,7.4-7.5,28.6c-1.3,5-3.1,10-4.3,18.1c-0.7,4.9-1.4,10.6-1.4,10.6c-0.3,2.8-0.4,4.3-0.8,7.4c-1.3,10.5-2,12.4-3.2,20.9
    c-1.8,13.3-1.2,15.7-2.5,28.3c-1.9,18.9-5.7,35.5-6.5,35.4c-0.6-0.1,0.4-11.1,2.3-29.1c0.8-7.8,1.3-13.5,2-19.4
    c4.5-42.7,5.6-52.8,7.1-60.9c0.7-4,1.8-9,2.8-16.2c0.2-1.4,0.5-3.4,1-6.3c0.4-2.2,1.1-5.5,2.3-9.7c2-7.1,3.1-10.6,4.2-11.7
    c6.1-5.4,23,6.9,26.9,9.8c0.7,0.5,1.2,0.9,1.8,1.4c9.5,7.4,15.3,14.3,18.9,18.5c0,0,6.8,7.8,17.2,18.2
    c20.3,20.2,29.2,21.1,30.5,29.1c0.7,4.3-6.7,11.9-22.8,25.3c-29.2,24.2-47.2,37.7-47.2,37.7c-18.1,13.5-20.1,14.5-30.3,22.7
    c-10.8,8.7-14.9,12.8-25.3,21.2c-12.1,9.7-22.3,16.9-28.9,21.3C395.9,208.3,416.8,190.3,430.9,178z"/>
  <path class="st0" d="M487.5,153c0.4,0.1,0.8,0.2,1.2,0.2c0.1,0.2,0.3,0.5,0.4,0.9c0.1,0.5,0.1,0.9,0,1.1c-0.6,0.2-1.1,0.5-1.7,0.7
    c-0.1,0-0.7-0.2-1-0.8c-0.4-0.7-0.1-1.4,0-1.5C486.7,153.5,487.1,153.3,487.5,153z"/>
</g>
<g id="Calque_3">
</g>
</svg>